[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
forge-std = { version = "1.9.1" }
axis-core = { version = "0.5.1", url = "git@github.com:Axis-Fi/axis-core.git", commit = "c7c46a3d045c4818c08567c4c530f1c7670eb0ac" }
"@openzeppelin-contracts" = { version = "4.9.2" }
"@openzeppelin-contracts-upgradeable" = { version = "4.9.2" }
"@uniswap-v2-core" = { version = "1.0.1" }
"@uniswap-v3-core" = { version = "1.0.1-solc-0.8-simulate" }
g-uni-v1-core = { version = "0.9.9", url = "git@github.com:Axis-Fi/g-uni-v1-core.git", commit = "d6bcb6e811e86d36bc836c002eb2e9a2c73d29ca" }
"@uniswap-v2-periphery" = { version = "1.0.1", git = "git@github.com:Axis-Fi/uniswap-v2-periphery.git", rev = "b643a2589ea219ac662a6447048f604dc5a3a7bb" }
