[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  {access = "read-write", path = "./bytecode/"},
  {access = "read", path = "./script/"},
  {access = "read-write", path = "./deployments/"},
  {access = "read", path = "./dependencies/axis-core-0.5.1/script/env.json"},
]
ffi = true
solc_version = "0.8.19"
evm_version = "paris"

[fuzz]
runs = 1024

# Remappings are setup using remappings.txt, since forge seems to ignore remappings here

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
wrap_comments = false
ignore = [
  "lib/**",
  "src/lib/**",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
forge-std = { version = "1.9.1" }
axis-core = { version = "0.5.1", git = "git@github.com:Axis-Fi/axis-core.git", rev = "d07b3311771ea3162d99aa68689e40f4f4bd8135" }
"@openzeppelin-contracts" = { version = "4.9.2" }
"@openzeppelin-contracts-upgradeable" = { version = "4.9.2" }
"@uniswap-v2-core" = { version = "1.0.1" }
"@uniswap-v3-core" = { version = "1.0.1-solc-0.8-simulate" }
g-uni-v1-core = { version = "0.9.9", git = "git@github.com:Axis-Fi/g-uni-v1-core.git", rev = "d6bcb6e811e86d36bc836c002eb2e9a2c73d29ca" }
"@uniswap-v2-periphery" = { version = "1.0.1", git = "git@github.com:Axis-Fi/uniswap-v2-periphery.git", rev = "19be650786731dfe43cac3aac7a2d1f0731d18e2" }
solmate = { version = "6.7.0", git = "git@github.com:transmissions11/solmate.git", rev = "c892309933b25c03d32b1b0d674df7ae292ba925" }
clones-with-immutable-args = { version = "1.1.1", git = "git@github.com:wighawag/clones-with-immutable-args.git", rev = "f5ca191afea933d50a36d101009b5644dc28bc99" }
