name: test

on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # Providing the SSH key to the checkout action does not work with our config.
      # It likely is because of the install script wiping the lib/ directory.
      # For this reason, we disable submodule checkouts above, set up the SSH agent
      # with the provided key, and then run the install script.
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Dependencies
        run: |
          pnpm install
        id: install

      - name: Run lint check
        run: pnpm run lint:check

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Contract Sizes
        run: |
          forge --version
          pnpm run size
        id: sizes
